### ISSUE TITLE
stack-buffer-underflow in parse_font

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#158]
```
=================================================================
==105696==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7f382951c530 at pc 0x7f383078e15d bp 0x7f382951beb0 sp 0x7f382951b658
WRITE of size 1836 at 0x7f382951c530 thread T6
    #1 0x5589adb3fada in parse_font /work/sist2/third-party/libscan/libscan/font/font.c:167
    #2 0x5589ad963193 in parse /work/sist2/src/parsing/parse.c:157
    #3 0x5589adb28ac6 in parse_archive /work/sist2/third-party/libscan/libscan/arc/arc.c:154
    #4 0x5589ad9632da in parse /work/sist2/src/parsing/parse.c:164
    #5 0x5589ad958c81 in tpool_worker /work/sist2/src/tpool.c:137
    #6 0x7f38306d8608 in start_thread /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477
    #7 0x7f38305ff292 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122292)

Address 0x7f382951c530 is located in stack of thread T6 at offset 0 in frame
    #0 0x5589ad9617ac in parse /work/sist2/src/parsing/parse.c:49

  This frame has 4 object(s):
    [32, 196640) 'buf' (line 75) <== Memory access at offset 0 partially underflows this variable
    [196896, 196929) 'path_md5_str' (line 78)
    [196976, 197009) 'md5_str'
    [197056, 197120) 'doc' (line 52)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T6 created by T0 here:
    #0 0x7f383072c805 in pthread_create (/lib/x86_64-linux-gnu/libasan.so.5+0x3a805)
    #1 0x5589ad959ace in tpool_start /work/sist2/src/tpool.c:256
    #2 0x5589ad93a377 in sist2_scan /work/sist2/src/main.c:303
    #3 0x5589ad93f663 in main /work/sist2/src/main.c:597
    #4 0x7f38305040b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: stack-buffer-underflow (/lib/x86_64-linux-gnu/libasan.so.5+0x9c15c) 
Shadow bytes around the buggy address:
  0x0fe78529b850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b860: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b870: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b880: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b890: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe78529b8a0: 00 00 00 00 00 00[f1]f1 f1 f1 00 00 00 00 00 00
  0x0fe78529b8b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b8c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b8e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe78529b8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==105696==ABORTING
```

**Comment by simon987** [comment]
Fixed in https://github.com/simon987/sist2/commit/a01f6dff1f993bb6dcda8e72996e0a094a6f88c1
