### ISSUE TITLE
segmentation fault in exec-script

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#166]
- SIST2 Version: `v2.10.2`

**Command with arguments** 
`./sist2 exec-script --es-index sist2-demo --es-url http://192.168.1.70:9200 --script-file ./script ./linux.idx/`

**Describe the bug**
```
ASAN:DEADLYSIGNAL
=================================================================
==6006==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fed90131185 bp 0x7ffe4880ae70 sp 0x7ffe4880a5e8 T0)
==6006==The signal is caused by a READ memory access.
==6006==Hint: address points to the zero page.
    #0 0x7fed90131184  (/lib/x86_64-linux-gnu/libc.so.6+0x182184)
    #1 0x7fed9020d38b  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x5238b)
    #2 0x5581639f3c8c in create_indexer /drone/src/src/index/elastic.c:315
    #3 0x5581639f1d4e in execute_update_script /drone/src/src/index/elastic.c:73
    #4 0x55816398c6fd in sist2_exec_script /drone/src/src/main.c:433
    #5 0x558163990418 in main /drone/src/src/main.c:622
    #6 0x7fed8ffd7cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
    #7 0x55816397d609 in _start (/root/docker/sist2_demo/sist2-demo/sist2-x64-linux-debug+0x17d609)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x182184) 
==6006==ABORTING
```

**Comment by simon987** [comment]
Fixed in d5a47b8dabcbff1ce919039c396be0ad0417598c
