### ISSUE TITLE
BUG: ocr-lang is wrong data type in sist2-admin

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#328]

**Comment by jimtalksdata** [comment]
Is this the same bug as selecting "eng" in jobs creates this?
```

sist2-admin  | ERROR:    Exception in ASGI application
sist2-admin  | Traceback (most recent call last):
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
sist2-admin  |     result = await app(  # type: ignore[func-returns-value]
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
sist2-admin  |     return await self.app(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
sist2-admin  |     await super().__call__(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
sist2-admin  |     await self.middleware_stack(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
sist2-admin  |     raise exc
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
sist2-admin  |     await self.app(scope, receive, _send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
sist2-admin  |     await self.simple_response(scope, receive, send, request_headers=headers)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
sist2-admin  |     await self.app(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
sist2-admin  |     raise exc
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
sist2-admin  |     await self.app(scope, receive, sender)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
sist2-admin  |     raise e
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
sist2-admin  |     await self.app(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
sist2-admin  |     await route.handle(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
sist2-admin  |     await self.app(scope, receive, send)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
sist2-admin  |     response = await func(request)
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 227, in app
sist2-admin  |     solved_result = await solve_dependencies(
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 571, in solve_dependencies
sist2-admin  |     ) = await request_body_to_args(  # body_params checked above
sist2-admin  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 706, in request_body_to_args
sist2-admin  |     v_, errors_ = field.validate(value, values, loc=loc)
sist2-admin  |   File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
sist2-admin  |   File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
sist2-admin  |   File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
sist2-admin  |   File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
sist2-admin  |   File "pydantic/main.py", line 712, in pydantic.main.BaseModel.validate
sist2-admin  |   File "/root/sist2-admin/sist2_admin/jobs.py", line 49, in __init__
sist2-admin  |     super().__init__(**kwargs)
sist2-admin  |   File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__
sist2-admin  |   File "pydantic/main.py", line 1077, in pydantic.main.validate_model
sist2-admin  |   File "pydantic/fields.py", line 898, in pydantic.fields.ModelField.validate
sist2-admin  |   File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
sist2-admin  |   File "pydantic/class_validators.py", line 287, in pydantic.class_validators._generic_validator_cls.lambda5
sist2-admin  |   File "/root/sist2-admin/sist2_admin/jobs.py", line 63, in validate_etag
sist2-admin  |     s = values["name"] + values["scan_options"].json() + values["index_options"].json() + values["cron_expression"]
sist2-admin  | KeyError: 'scan_options'
```

**Comment by simon987** [comment]
> Is this the same bug as selecting "eng" in jobs creates this?

yes

**Comment by simon987** [comment]
I'm logging off for today but this should be fixed in the `x64-linux` image when this is done: https://ci.simon987.net/simon987/sist2/243
