### ISSUE TITLE
sist2-admin deadlock with multiple scheduled jobs

### ISSUE THREAD

**Issue by Badlee2020** [simon987/sist2#346]
Hi, 

After a "task" fails due to any reason (corrupt file, unreadable, etc), all scheduled tasks then recieve this error. Manually started tasks continue to work without any problem.

below is the error:
------

Exception in thread timer:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/sist2-admin/sist2_admin/cron.py", line 27, in _cron_thread
    _check_schedule(db, run_job)
  File "/root/sist2-admin/sist2_admin/cron.py", line 19, in _check_schedule
    run_job(job)
  File "/root/sist2-admin/sist2_admin/app.py", line 141, in _run_job
    db["jobs"][job.name] = job
  File "/usr/local/lib/python3.10/dist-packages/hexlib/db.py", line 210, in __setitem__
    self.setitem_pydantic(key, value)
  File "/usr/local/lib/python3.10/dist-packages/hexlib/db.py", line 200, in setitem_pydantic
    self.__setitem__(key, {
  File "/usr/local/lib/python3.10/dist-packages/hexlib/db.py", line 213, in __setitem__
    with sqlite3.connect(self._state.dbfile, **self._state.dbargs) as conn:
sqlite3.OperationalError: database is locked

------

The only workaround is deleting the "state.db" and retrying.

**Comment by simon987** [comment]
How many scheduled tasks were you running? Were they triggering all at the same time?
The 3.X release hopefully should fix the `database is locked` error, let me know

**Comment by Badlee2020** [comment]
In Version 3.0.6, I cannot successful test it. It seems to be somehow broken. When running one index(task) scheduled one a day the whole admin page seems to die. There are no errors in the docket log. An admin log is not created. The admin page immediately looses all the content. You just see the blue bars showing its loading. On the task page all the logs are gone. After about 2 minutes, the admin page is unreachable, the CPU usage on the container is minimal. But the search site is still available and working. Not much help i know, but there are no logs or anything

**Comment by simon987** [comment]
Should be fixed in [7eb0641](https://github.com/simon987/sist2/commit/7eb064162e3cd14ee96c85e5d47549c2cfb81437)
