### ISSUE TITLE
Sist-Admin: Fails to Kill job

### ISSUE THREAD

**Issue by dpieski** [simon987/sist2#416]
**Device Information (please complete the following information):**
 - Deployment: `[Linux, Linux ARM64 or Docker]` Docker
 - SIST2 Version: `[e.g., v2.9.0]` 3.2.1
 - Elasticsearch Version *(if relevant)* : `` 7.17.9

**Describe the bug**

The `index` task locked up. I selected the `kill` option for the job. The job was not killed. 
This is the error:
```powershell
2023-08-24 21:36:26 [INFO] Killing task 0c4ede0c-035c-4809-8a82-da595d243014 (pid=None)
INFO:     192.168.100.12:15988 - "POST /api/task/0c4ede0c-035c-4809-8a82-da595d243014/kill HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/sist2-admin/sist2_admin/app.py", line 133, in kill_job
    return task_queue.kill_task(task_id)
  File "/root/sist2-admin/sist2_admin/jobs.py", line 372, in kill_task
    os.kill(pid, signal.SIGTERM)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by dpieski** [comment]
Maybe associated:
https://github.com/simon987/sist2/issues/397#issuecomment-1661189870_
#399

**Comment by TheBig-O** [comment]
I'm having the same issue. Scans get to a certain point and then a child process terminates but the scan neither exits nor completes. Any thoughts?

```
[WARNING /host/Calibre Library/M. David Green/Scrum_ Novice to Ninja (9)/Scrum_ Novice to Ninja - M. David Green.pdf] FZ: aborting process from uncaught error!
2023-09-23 22:50:29 [DEBUG tpool.c] Child process terminated with status code 1
```

**Comment by shyyio** [comment]
Fixed in v4.0.x.
