### ISSUE TITLE
Models are not downloaded in the browser

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#466]
**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04, WSL2`
 - Deployment: Docker
 - Browser *(if relevant)*: chromium, firefox windows
 - SIST2 Version: v2.9.0
 
**Describe the bug**
The models for analyzing documents are not downloaded in the browser

**Steps To Reproduce**
Please be specific!
1. search for a pdf
2. click on the info button
3. select a model and click analyze

**Expected behavior**
It should analyze the document?
**Actual Behavior**

**Screenshots**
![image](https://github.com/simon987/sist2/assets/8519469/f965de43-ceb1-47bd-9a79-2891d8624bc0)

![image](https://github.com/simon987/sist2/assets/8519469/f642a5e2-d3c7-4ba4-8202-a24a4a0f384b)

**Additional context**
```
chunk-vendors.js:2 RangeError: offset is out of bounds
    at Uint8ClampedArray.set (<anonymous>)
    at L (index.js:1:12866)
    at async Di.loadModel (index.js:1:95993)
    at async Promise.all (:14090/index 1)
    at async Di.init (index.js:1:95788)
    at async t.getMlModel (index.js:1:99406)
    at async t.mlAnalyze (index.js:1:99788)

```

**Comment by simon987** [comment]
Can you update to the latest version (3.4.0) and try again? I think that the models it's downloading are incompatible with the newest version

**Comment by gerroon** [comment]
I can try it, I am using docker compose. What tags shall I use?

**Comment by simon987** [comment]
`simon987/sist2:3.4.0-x64-linux`

**Comment by gerroon** [comment]
Thanks, I still have the same errors

**Comment by MrReSc** [comment]
Where can I find the Analyze button?

**Comment by ptf-laurentvetter** [comment]
> Where can I find the Analyze button?

1. search for a pdf
2. click on the info button
3. select a model and click analyze

Does not work in `simon987/sist2:x64-linux`, which runs 3.5.0:

<img width="1170" height="215" alt="Image" src="https://github.com/user-attachments/assets/993463b9-f7e0-484c-b685-26d8663e06f6" />

**Comment by shyyio** [comment]
Stale issue; NER has been removed.

Also fixed server crash when requesting an unknown model in f2e3cfa
