### ISSUE TITLE
segfault while scanning .epub

### ISSUE THREAD

**Issue by simon987** [simon987/sist2#82]
v2.7.1

```
    ASAN:SIGSEGV
=================================================================
==13647==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000964a28 bp 0x000000000000 sp 0x7fd244367c20 T1)
    #0 0x964a27 in generate_boxes (/root/sist2_debug_2.7.1+0x964a27)
    #1 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #2 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #3 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #4 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #5 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #6 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #7 0x9645d9 in generate_boxes (/root/sist2_debug_2.7.1+0x9645d9)
    #8 0x9653f5 in fz_parse_html (/root/sist2_debug_2.7.1+0x9653f5)
    #9 0x959f0a in epub_parse_chapter.isra.3 (/root/sist2_debug_2.7.1+0x959f0a)
    #10 0x95a90b in epub_parse_header (/root/sist2_debug_2.7.1+0x95a90b)
    #11 0x95aa6a in epub_init (/root/sist2_debug_2.7.1+0x95aa6a)
    #12 0x5cc220 in parse_ebook_mem /server/agent/work/f1ce04c709a195f3/third-party/libscan/libscan/ebook/ebook.c:226
    #13 0x5cce2a in parse_ebook /server/agent/work/f1ce04c709a195f3/third-party/libscan/libscan/ebook/ebook.c:378
    #14 0x49e9a6 in parse /server/agent/work/f1ce04c709a195f3/src/parsing/parse.c:130
    #15 0x496829 in tpool_worker /server/agent/work/f1ce04c709a195f3/src/tpool.c:130
    #16 0x7fd247c76608 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x9608)
    #17 0x7fd247822102 in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x122102)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 generate_boxes
Thread T1 created by T0 here:
    #0 0x7fd247cce1e3 in pthread_create (/root/libasan.so.2+0x361e3)
    #1 0x49aa0d in tpool_start /server/agent/work/f1ce04c709a195f3/src/tpool.c:248
    #2 0x48d4f0 in sist2_scan /server/agent/work/f1ce04c709a195f3/src/main.c:219
    #3 0x486472 in main /server/agent/work/f1ce04c709a195f3/src/main.c:475
    #4 0x7fd2477270b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

==13647==ABORTING
```

[file.epub.gz](https://github.com/simon987/sist2/files/4941835/file.epub.gz)

**Comment by simon987** [comment]
Seems to be fixed in mupdf 1.17.0, see https://github.com/microsoft/vcpkg/pull/12483
